[platformio]
core_dir = ../.platformio-home
default_envs = m5stick-cplus2

[env:m5stick-cplus2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.variant = m5stack_stickc_plus2
build_flags =
  -pipe
lib_deps =
  m5stack/M5Unified@0.2.17
  fcz2/m5-tone-output@0.1.4
